# Generated by Django 2.2.7 on 2019-11-11 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191111_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='registered',
            new_name='selected',
        ),
    ]
