# Generated by Django 2.2.7 on 2019-11-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191111_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gift_bought',
            field=models.BooleanField(default=False),
        ),
    ]
