# Generated by Django 2.2.7 on 2019-12-02 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191201_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='gift_bought',
            new_name='is_santa',
        ),
    ]
