# Generated by Django 2.2.7 on 2019-12-02 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191202_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_santa',
            new_name='santa_notified',
        ),
    ]
